@startuml sample
package Logger {
    class Logger {
        void __construct(Driver driver)
        string log(string comment)
    }
    class Driver {
        string output()
    }
}

Logger ..> Driver
@enduml